version: "3.8"

services:
  seso-redis-prep:
    container_name: seso-redis-prep
    image: redis:6.0.9
    ports:
      - "6379:6379"
  seso-postgres-prep:
    container_name: seso-postgres-prep
    image: postgres:13.1
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres-data:
networks:
  seso:
