export enum orgTypes {
  FLC = "FLC",
  GROWER = "GROWER",
}
export enum employmentTypes {
  EMPLOYEE = "EMPLOYEE",
  LABORER = "LABORER",
}
export enum jobTitleTypes {
  BEEKEEPER = "BEEKEEPER",
  FARM_LABORER = "FARM_LABORER",
  FARM_WORKER = "FARM_WORKER",
  FARMWORKERS_AND_LABORERS_CROP = "FARMWORKERS_AND_LABORERS_CROP",
  FIELD_SHED_SUPPORT_WORKERS = "FIELD_SHED_SUPPORT_WORKERS",
  FIELD_WORKER = "FIELD_WORKER",
  GENERAL_FARMWORKERS = "GENERAL_FARMWORKERS",
  GOAT_HERDER = "GOAT_HERDER",
  RANGE_LIVESTOCK_WORKER = "RANGE_LIVESTOCK_WORKER",
  SHEEP_HERDER = "SHEEP_HERDER",
  VINEYARD_WORKER = "VINEYARD_WORKER",
}
export enum otpStatus {
  COMPLETE = "COMPLETE",
  PENDING = "PENDING",
}
